site_name: Redes locales
site_url: https://joperpu.github.io/rl2526
theme:
  name: material
  language: es
  favicon: assets/images/logo.ico
  features:
    - content.code.copy
  palette: 
    - scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: "assets/images/logo.png"
nav:
  - Página principal: index.md
  - Unidad 1 - Caracterización de las redes de comunicación:
    - Teoría UD1: ud1.md
    - Práctica 1.1: pr1.1.md
    - Práctica 1.2: pr1.2.md
    - Práctica 1.3: pr1.3.md
    - Práctica 1.4: pr1.4.md
  - Unidad 2 - Normalización de las redes:
    - Teoría UD2: ud2.md
    - Práctica 2.1: pr2.1.md
    - Práctica 2.2: pr2.2.md
    - Práctica 2.3: pr2.3.md
    - Práctica 2.4: pr2.4.md
    - Práctica 2.5: pr2.5.md
    - Práctica 2.6: pr2.6.md
    - Práctica 2.7: pr2.7.md
    - Práctica 2.8: pr2.8.md
    - Práctica 2.9: pr2.9.md
    - Práctica 2.10: pr2.10.md
    - Práctica 2.11: pr2.11.md
  - Unidad 3 - Prevención de riesgos laborales y de protección ambiental:
    - Teoría UD3: ud3.md
    - Práctica 3.1: pr3.1.md
    - Práctica 3.2: pr3.2.md
  - Unidad 4 - Organización física de la redes:
    - Teoría UD4: ud4.md
    - Práctica 4.1: pr4.1.md
    - Práctica 4.2: pr4.2.md
    - Práctica 4.3: pr4.3.md
    - Práctica 4.4: pr4.4.md
    - Práctica 4.5: pr4.5.md
    - Práctica 4.6: pr4.6.md
  - Unidad 5 - Instalación y configuración de equipos en una red:
    - Teoría UD5: ud5.md
    - Práctica 5.1: pr5.1.md
  - Unidad 6 - Interconexión de equipos en redes de área local:
    - Teoría UD6: ud6.md
    - Práctica 6.1: pr6.1.md
    - Práctica 6.2: pr6.2.md
    - Ejercicios de repaso: ej.md

copyright: "2026 José María Pérez Puentes - Licencia CC BY-NC-SA 4.0"

extra:
  generator: true

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - admonition
  - pymdownx.details